### ISSUE TITLE
Add README.md to your repository

### ISSUE THREAD

**Issue by extsoft** [oteplova/AT_Bootcamp#2]

**Comment by oteplova** [comment]
Completed. @extsoft please check.

**Comment by oteplova** [comment]
Completed. @extsoft  please check.

**Comment by extsoft** [comment]
@oteplova please add `.md` extension to the file.

**Comment by oteplova** [comment]
Completed. @extsoft  please check.

**Comment by extsoft** [comment]
@oteplova accepted.
