### ISSUE TITLE
Use separate list for teachers 

### ISSUE THREAD

**Issue by extsoft** [oteplova/AT_Bootcamp#4]
https://github.com/oteplova/AT_Bootcamp/blob/537d027b7faef4eab7a5520e15e2a6539de0bc6d/src/main/java/net/comments/sample/App.java#L34

Avoid casting objects, it's a bad practice. 

So, you could:
- use the separate list of teachers
- use the teachers without the list (as there is only one teacher per subject)

Affects #1

**Comment by oteplova** [comment]
Complete. @extsoft  please check

**Comment by extsoft** [comment]
@oteplova accepted
