### ISSUE TITLE
Update Room interface

### ISSUE THREAD

**Issue by extsoft** [oteplova/AT_Bootcamp#5]
Please use `void` instead of `boolean` in 
https://github.com/oteplova/AT_Bootcamp/blob/537d027b7faef4eab7a5520e15e2a6539de0bc6d/src/main/java/net/comments/sample/Room.java#L9.

And if you need a list of students allocated in the room, it's a good idea to add one more method to the interface: `Person[] members` or `List<Person> members`.

Affects #1.

**Comment by oteplova** [comment]
Complete. @extsoft please check

**Comment by oteplova** [comment]
Updated. @extsoft please check.

**Comment by extsoft** [comment]
@oteplova 
1. https://github.com/oteplova/AT_Bootcamp/blob/537d027b7faef4eab7a5520e15e2a6539de0bc6d/src/main/java/net/comments/sample/TrainingRoomLimited.java#L10 has to be final.
2. There is no a requirement to have only one teacher in the room.
3. A `Room` doesn't know anything about what persons do inside. So, please move out logic related to the learning.
4. Why does `accept` return a boolean?

**Comment by oteplova** [comment]
@extsoft  I've removed that 'accept' method returns boolean.  Now it's void.

**Comment by oteplova** [comment]
@extsoft  I don't why but something strange happens, and old code is shown. I'll check this.

**Comment by extsoft** [comment]
@oteplova 
1. Solved
2. Still present. A teacher is a person also.
3. Still present. Please update the message according to the requirements from #1 
4. Solved.
